proyecto/Models/Libro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestamo = new HashSet<Prestamo>();
        }
    
        public int id_libro { get; set; }
        public string titulo { get; set; }
        public string publicacion { get; set; }
        public int id_categoria { get; set; }
        public int id_autor { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo> Prestamo { get; set; }
    }
}

proyecto/Models/ViewModels/LibroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace proyecto.Models.ViewModels
{
    public class LibroViewModel
    {
    }
}

proyecto/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using proyecto.Models;

namespace proyecto.Controllers
{
    public class LibroController : Controller
    {
        private proyectoclaseEntities db = new proyectoclaseEntities();

        // GET: Libro
        public ActionResult Index(string autor,string categoria)
        {
            var libro = db.Libro.Include(l => l.Autor).Include(l => l.Categoria);
            if (!String.IsNullOrEmpty(autor))
            {
                libro = libro.Where(s => s.Autor.nombre.Contains(autor));
            }
            if (!String.IsNullOrEmpty(categoria))
            {
                libro = libro.Where(s => s.Categoria.categoria1.Contains(categoria));
            }
            return View(libro.ToList());
        }

        // GET: Libro/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // GET: Libro/Create
        public ActionResult Create()
        {
            ViewBag.id_autor = new SelectList(db.Autor, "id_autor", "nombre");
            ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "categoria1");
            return View();
        }

        // POST: Libro/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_libro,titulo,publicacion,id_categoria,id_autor")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                db.Libro.Add(libro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_autor = new SelectList(db.Autor, "id_autor", "nombre", libro.id_autor);
            ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "categoria1", libro.id_categoria);
            return View(libro);
        }

        // GET: Libro/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_autor = new SelectList(db.Autor, "id_autor", "nombre", libro.id_autor);
            ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "categoria1", libro.id_categoria);
            return View(libro);
        }

        // POST: Libro/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_libro,titulo,publicacion,id_categoria,id_autor")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(libro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_autor = new SelectList(db.Autor, "id_autor", "nombre", libro.id_autor);
            ViewBag.id_categoria = new SelectList(db.Categoria, "id_categoria", "categoria1", libro.id_categoria);
            return View(libro);
        }

        // GET: Libro/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // POST: Libro/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Libro libro = db.Libro.Find(id);
            db.Libro.Remove(libro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

proyecto/Views/Libro/Create.cshtml
@model proyecto.Models.Libro

@{
    ViewBag.Title = "Ingresar Libro Nuevo";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.publicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.publicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.publicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categoria, "id_categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_autor, "id_autor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_autor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al Indice", "Index")
</div>

proyecto/Views/Libro/Delete.cshtml
@model proyecto.Models.Libro

@{
    ViewBag.Title = "Eliminar un Libro";
}

<h2>Eliminar Libro de la Biblioteca</h2>

<h3>¿Estas Seguro de eliminar lo siguiente?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor.nombre)
        </dd>

        <dt>
            Categoria
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar al Indice", "Index")
        </div>
    }
</div>

proyecto/Views/Libro/Details.cshtml
@model proyecto.Models.Libro

@{
    ViewBag.Title = "Informacion";
}

<h2>Informacion de Libro</h2>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.publicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor.nombre)
        </dd>

        <dt>
            Categoria
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id_libro }) |
    @Html.ActionLink("Regresar al Indice", "Index")
</p>

proyecto/Views/Libro/Edit.cshtml
@model proyecto.Models.Libro

@{
    ViewBag.Title = "Editar Libro";
}

<h2>Editar Libro</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_libro)

        <div class="form-group">
            @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.publicacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.publicacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.publicacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_categoria, "id_categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_categoria", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_autor, "id_autor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_autor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_autor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

proyecto/Views/Libro/Index.cshtml
@model IEnumerable<proyecto.Models.Libro>

@{
    ViewBag.Title = "Menu de Libros";
}

<h2>Indice de Libros</h2>

<p>
    <div class="row" style="text-align:right;padding:5px;">
        <a href="~/Libro/Create" class="btn btn-primary"> Registrar Nuevo Libro</a>
    </div>
</p>

@using (Html.BeginForm("Index","Libro"))
{
<p>
    Filtrar por Autor: @Html.TextBox("autor")
    Filtrar por Categoria: @Html.TextBox("categoria")


    <input type="submit" value="Search" />
</p>
}
<table class="table">
    <tr>
        <th>
            Titulo del libro
        </th>
        <th>
            Publicacion
        </th>
        <th>
            Autor
        </th>
        <th>
            Categoria
        </th>
        <th>Acciones</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.publicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Categoria.categoria1)
            </td>
            <td>
                <a class="btn btn-warning" href="~/Libro/Edit/@item.id_libro">Editar</a>
                <a class="btn btn-success" href="~/Libro/Details/@item.id_libro">Informacion</a>
                <a class="btn btn-danger" href="~/Libro/Delete/@item.id_libro">Eliminar</a>

                <!--@Html.ActionLink("Edit", "Edit", new { id=item.id_libro }) |
                @Html.ActionLink("Details", "Details", new { id=item.id_libro }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id_libro })-->
            </td>
        </tr>
    }

</table>