proyecto/Models/Autor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autor()
        {
            this.Libro = new HashSet<Libro>();
        }
    
        public int id_autor { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libro> Libro { get; set; }
    }
}

proyecto/Models/ViewModels/AutorViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace proyecto.Models.ViewModels
{
    public class AutorViewModel
    {

        public int id_autor { set; get; }

        [Required]
        [Display(Name = "Nombre")]
        public String nombre { set; get; }
    }
}

proyecto/Controllers/AutorController.cs
using proyecto.Models;
using proyecto.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace proyecto.Controllers
{
    public class AutorController : Controller
    {
        
        public ActionResult Index()
        {
            List<ListAutorViewModel> lst;
            using (proyectoclaseEntities db = new proyectoclaseEntities())
            {
                lst = (from d in db.Autor
                       select new ListAutorViewModel
                       {
                           id_autor = d.id_autor,
                           nombre = d.nombre,

                       }).ToList();

            }
            return View(lst);
        }
        public ActionResult Nuevo()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Nuevo(AutorViewModel model) {


            try {

                if (ModelState.IsValid)
                {
                    using (proyectoclaseEntities db = new proyectoclaseEntities())
                    {
                        var oAutor = new Autor();
                        oAutor.nombre = model.nombre;
                        db.Autor.Add(oAutor);
                        db.SaveChanges();


                    }
                    return Redirect("~/Autor/");
                }
                return View(model);
            } catch (Exception EX)
            {


            }
            return View();
        }
        public ActionResult Editar(int id)
        {
            AutorViewModel modelo = new AutorViewModel();
            using (proyectoclaseEntities db = new proyectoclaseEntities())
            {
                var elemento = db.Autor.Find(id);
                modelo.nombre = elemento.nombre;
                modelo.id_autor = elemento.id_autor;

            }
                return View(modelo);
        }
        [HttpPost]
        public ActionResult Editar(AutorViewModel model)
        {


            try
            {

                if (ModelState.IsValid)
                {
                    using (proyectoclaseEntities db = new proyectoclaseEntities())
                    {
                        var oAutor = db.Autor.Find(model.id_autor);
                        oAutor.nombre = model.nombre;
                        db.Entry(oAutor).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();


                    }
                    return Redirect("~/Autor/");
                }
                return View(model);
            }
            catch (Exception EX)
            {


            }
            return View();
        }
        [HttpGet]
        public ActionResult Eliminar(int id)
        {
            AutorViewModel modelo = new AutorViewModel();
            using (proyectoclaseEntities db = new proyectoclaseEntities())
            {
                
                var elemento = db.Autor.Find(id);
                db.Autor.Remove(elemento);
                db.SaveChanges();
            }
            return Redirect("~/Autor/");
        }
    }


}

proyecto/Views/Autor/Editar.cshtml
@model  proyecto.Models.ViewModels.AutorViewModel
@{
    ViewBag.Title = "Editar Autor";
}

<h2>Editar Autor</h2>


@using (Html.BeginForm("Editar", "Autor", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">
        @Html.HiddenFor(d=>d.id_autor);
            @Html.LabelFor(d => d.nombre)
            @Html.TextBoxFor(d => d.nombre, "", new { @class = "form-control" })
        </div>
        <br>
        <div style="text-align:right;">
            <input type="submit" value="Editar Cambios" class="btn btn-primary" />
        </div>
    </div>
}

proyecto/Views/Autor/Index.cshtml
@model List<proyecto.Models.ViewModels.ListAutorViewModel>
@{
    ViewBag.Title = "Listado de Autores";
}

<h2>Listado de Autores</h2>
<div class="row" style="text-align:right;padding:5px;">
    <a href="~/Autor/Nuevo" class="btn btn-primary"> Nuevo Autor</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
            
            @foreach (var elemento in Model)
            {
                <tr>
                    <td>@elemento.id_autor</td>
                    <td>@elemento.nombre</td>
                    <td>
                        <a class="btn btn-warning"href="~/Autor/Editar/@elemento.id_autor">Editar</a>
                        <a class="btn btn-danger"href="~/Autor/Eliminar/@elemento.id_autor">Eliminar</a>
                    </td>
                </tr>
            }
        </table>
    </div>


</div>

proyecto/Views/Autor/Nuevo.cshtml
@model  proyecto.Models.ViewModels.AutorViewModel
@{
    ViewBag.Title = "Nuevo Autor";
}

<h2>Nuevo Autor</h2>


@using (Html.BeginForm("Nuevo", "Autor", FormMethod.Post)) {
<div class="row">
    <div class="col-md-12">
        @Html.LabelFor(d=>d.nombre)
        @Html.TextBoxFor(d=>d.nombre, "", new {@class= "form-control"})
    </div>
    <br>
<div style="text-align:right;">
    <input type="submit" value="Guardar" class="btn btn-primary"/>
</div>
</div>
}